---
deployment:
  tasks:
    - /bin/cp index.php /home/seafilmz/public_html/
    - /bin/cp about.php /home/seafilmz/public_html/
    - /bin/cp built-with.php /home/seafilmz/public_html/
    - /bin/cp streaming-services.php /home/seafilmz/public_html/
    - /bin/cp sitemap.php /home/seafilmz/public_html/
    - /bin/cp washington-cities.php /home/seafilmz/public_html/
    - /bin/cp oregon-cities.php /home/seafilmz/public_html/
    - /bin/cp idaho-cities.php /home/seafilmz/public_html/
    - /bin/cp alaska-cities.php /home/seafilmz/public_html/
    - /bin/cp seattle-movies.php /home/seafilmz/public_html/
    - /bin/cp seattle-actors.php /home/seafilmz/public_html/
    - /bin/cp portland-oregon-movies.php /home/seafilmz/public_html/
    - /bin/cp portland-oregon-actors.php /home/seafilmz/public_html/
    - /bin/cp movie-details.php /home/seafilmz/public_html/
    - /bin/cp people-details.php /home/seafilmz/public_html/
    - /bin/cp city-details.php /home/seafilmz/public_html/
    - /bin/cp js/website-name-stands-for.js /home/seafilmz/public_html/js/
    - /bin/cp js/popsicle-answer.js /home/seafilmz/public_html/js/
    - /bin/cp js/mobile-nav.js /home/seafilmz/public_html/js/
    - /bin/cp templates/movie-search-form.php /home/seafilmz/public_html/templates/
    - /bin/cp queryfunctions/state-cities-functions.php /home/seafilmz/public_html/queryfunctions/