---
deployment:
tasks:
- export
DEPLOYPATH=/home/seafilmz/public_html/
- /bin/cp index.php
$DEPLOYPATH
- /bin/cp about.php
$DEPLOYPATH
- /bin/cp streaming-services.php
$DEPLOYPATH
- /bin/cp sitemap.php
$DEPLOYPATH